### Obtener todas las localidades
GET http://localhost:3000/api/localidades


### Obtener una localidad
GET http://localhost:3000/api/localidades/1b587da1-a2d0-4405-8381-850e35068ab9


### Crear una nueva localidad
POST http://localhost:3000/api/localidades
Content-Type: application/json

{
    "nombre_localidad": "Pergamino"
}


### Modificar una localidad (PUT - Recurso completo e idempotente)
PUT http://localhost:3000/api/localidades/1b587da1-a2d0-4405-8381-850e35068ab9
Content-Type: application/json

{
    "nombre_localidad": "Buenos Aires"
}


### Modificar una localidad (PATCH - Recurso parcial)
PATCH http://localhost:3000/api/localidades/1b587da1-a2d0-4405-8381-850e35068ab9
Content-Type: application/json

{
    "nombre_localidad": "Bs As"
}


### Borrar una localidad
DELETE http://localhost:3000/api/localidades/1b587da1-a2d0-4405-8381-850e35068ab9