

### Get de editorial
GET http://Localhost:3000/api/editoriales/2/libros



### Post de editorial
POST http://localhost:3000/api/editoriales/2/libros
Content-Type: application/json

{
    "isbn": "Nose",
    "titulo": "Esto no va a funcionar ni a palo",
    "idioma": "Español",
    "descripcion": "Ni chanse",
    "precio": 10.000,
    "fecha_edicion": "2019-10-10",
    "autores": ["pepita", "pepito"],
    "editorial": "Dios sabe",
    "categorias": ["Terror", "Suspenso"],
    "formatos": ["Digital", "Fisico"]
}



