

### Get de editorial
GET http://Localhost:3000/api/editoriales/6542adeadaa549f540274b3a/libros



### Get de editorial por nombre
GET http://Localhost:3000/api/editoriales/6542adeadaa549f540274b3a


### Post de editorial
POST http://localhost:3000/api/editoriales/6542adeadaa549f540274b3a/libros
Content-Type: application/json

{
    "id": "1",
    "isbn": "Nose",
    "titulo": "Esto no va a funcionar ni a palo",
    "idioma": "Español",
    "descripcion": "Ni chanse",
    "precio": 10.000,
    "fecha_edicion": "2019-10-10",
    "autores": ["pepita", "pepito"],
    "editorial": "Dios sabe",
    "categorias": ["Terror", "Suspenso"],
    "formatos": ["Digital", "Fisico"]
}



### Delete de editorial
DELETE http://localhost:3000/api/editoriales/6522a452176057b2ea4ed843