### GET all tipos de servicio 
http://localhost:3000/api/serviceTypes


### POST a character

# @name createPlomeria
POST http://localhost:3000/api/serviceTypes
Content-Type: application/json

{
  "nombreTipo":"3Plomeria",
  "descripcionTipo":"Sevicios de plomeria y fontaneria para toda la casa"
}

### ID
@id = {{createPlomeria.response.body.data.id}}

### GET one Tipo de Servicio
http://localhost:3000/api/serviceTypes/{{id}}

### PUT a character
PUT http://localhost:3000/api/serviceTypes/{{id}}
Content-Type: application/json

{
  "users": [
    1
  ]
}


### POST a character
# @name createTipoToDelete
POST http://localhost:3000/api/serviceTypes
Content-Type: application/json

{
  "nombreTipo": "Electricidad",
  "descripcionTipo": "Servicios de electricidad y reparaciones electricas"
}
### DELETE a character
@idToDelete = {{createTipoToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/serviceTypes/1

### PATCH a character
PATCH http://localhost:3000/api/serviceTypes/5
Content-Type: application/json

{
  "nombreTipo":"Fontaneria",
  "descripcionTipo":"Servicios de fontaneria y reparaciones de fontaneria"
}

### DELETE a character
