### obtener todos los eventos

GET http://localhost:3000/api/eventos 

### obtener un evento

GET http://localhost:3000/api/eventos/1233

### crear un nuevo evento

POST http://localhost:3000/api/eventos
Content-Type: application/json

{
    "idEvento": 1233,
    "nombre":"evento popcddddddddd",
    "cuposGral":99999,
    "descripcion":"prueba 1",
    "fotoEvento":0,
    "fecha":"ayer",
    "hora":1500
}

### modificar un evento (PUT - recurso completo e inempotente)
PUT http://localhost:3000/api/eventos/123
Content-Type: application/json

{
    "nombre":"evento rock",
    "cuposGral":10,
    "descripcion":"prueba 2",
    "fotoEvento":0,
    "fecha":"ayer",
    "hora":1500
}
//NO ANDA SI PONGO EL ID EN LA API, SI LO PONGO EN EL JSON SI


### modificar un evento (PATCH - recurso parcial)
PATCH http://localhost:3000/api/eventos/123
Content-Type: application/json

{
    "cuposGral": 100,
    "descripcion": "prueba 3"
}
//NO ANDA SI PONGO EL ID EN LA API, SI LO PONGO EN EL JSON SI


### Borrar un evento
DELETE http://localhost:3000/api/eventos/123123