### Obtener todas las localidades
GET http://localhost:3000/api/localidades


### Obtener una localidad
GET http://localhost:3000/api/localidades/2


### Crear una nueva localidad
POST http://localhost:3000/api/localidades
Content-Type: application/json

{
    "nombre_localidad": "Pergamino",
    "id": 70
}


### Modificar una localidad (PUT - Recurso completo e idempotente)
PUT http://localhost:3000/api/localidades/5
Content-Type: application/json

{
    "nombre_localidad": "Perez"
}


### Modificar una localidad (PATCH - Recurso parcial)
PATCH http://localhost:3000/api/localidades/66a2e7f2123c9672e5ada8c6
Content-Type: application/json

{
    "nombre_localidad": "Bs As"
}


### Borrar una localidad
DELETE http://localhost:3000/api/localidades/70