### Obtener todas las politicas de sanción
GET http://localhost:3000/api/politicasSancion





### Subir politica de sanción

POST http://localhost:3000/api/politicasSancion
Content-Type: application/json

{
    "diasHasta": 14,
    "diasSancion": 10

}


### Actualizar autor con PATCH (parcialmente)

PATCH http://localhost:3000/api/politicasSancion/7
Content-Type: application/json

{
    
    "diasSancion": 8

}

### Delete de una politica por ID

DELETE  http://localhost:3000/api/politicaSancion/7