
### Obtener todos los libros
GET http://localhost:3000/api/politicaBiblioteca


### Crear politica de biblioteca SOLO UNA VEZ USAR.

POST http://localhost:3000/api/politicaBiblioteca
Content-Type: application/json

{
    "diasSancionMaxima": 180,
    "diasPrestamo": 15,
    "cantPendientes": 4

}

### Actualizar politica bilioteca con PUT
PUT http://localhost:3000/api/politicaBiblioteca
Content-Type: application/json

{
    "diasSancionMaxima": 666,
    "diasPrestamo": 30,
    "cantPendientes": 3

}