### Buscar todas las sanciones
GET http://localhost:3000/api/sanciones

### Buscar todas las sanciones de un socio
GET http://localhost:3000/api/socios/-12/sanciones

### Buscar una sanción por id
GET http://localhost:3000/api/sanciones/1
