### Obtener todos los autores
GET http://localhost:3000/api/autores/

### Obtener un autor
GET http://localhost:3000/api/autores/14

### Subir autor

POST http://localhost:3000/api/autores
Content-Type: application/json

{
    "nombre": "agostino",
    "apellido": "Borges"

}

### Delete de un autor por ID
DELETE  http://localhost:3000/api/autores/

### Subir autor2

POST http://localhost:3000/api/autores/
Content-Type: application/json

{
    "nombre": "EdgarBorrado",
    "apellido": "Allan Poe"

}

### Actualizar autor con PATCH (parcialmente)

PUT http://localhost:3000/api/autores/e
Content-Type: application/json

{
    
    "nombre": "Agostino",
    "apellido": "Peña"


}

