### Paso 1 retirar libros refactor

GET http://localhost:3000/api/prestamos/retirarLibrosPaso1R
Content-Type: application/json

{
    "idSocio": 1

}


### Retirar libros paso 2 refactor. 

GET http://localhost:3000/api/prestamos/retirarLibrosPaso2R
Content-Type: application/json

{
    "idSocio": 1,
    "idEjemplar": 1,
    "idLibro":1

}

### Retirar libros paso 3 refactor. 

POST http://localhost:3000/api/prestamos/retirarLibrosPaso3R
Content-Type: application/json

{
    "idSocio": 1,
    "ejemplares":[
      {
        "id": 1,
        "miLibro":4
      }
    ]

}

### Devolver un libro.

PATCH http://localhost:3000/api/prestamos/devolverLibro
Content-Type: application/json

{
    "idSocio": 4,
    "idEjemplar": 4,
    "idLibro":1

}

### Devolver un libro socio atrasado. Hacer modificaciones comentadas en el controlador.

PATCH http://localhost:3000/api/prestamos/devolverLibro
Content-Type: application/json

{
    "idSocio": 1,
    "idEjemplar": 1,
    "idLibro":4

}

### Devolver un libro socio atrasado. Hacer modificaciones comentadas en el controlador.

PATCH http://localhost:3000/api/prestamos/6/lineas/10/devolver
Content-Type: application/json

{
    "idSocio": 1

}