### Obtener todos los socios
GET http://localhost:3000/api/socios/


### Subir Socio

POST http://localhost:3000/api/socios
Content-Type: application/json

{
    "nombre": "Juan Pepe 5",
    "apellido": "Lopez",
    "email": "agosLopez@gmail.com",
    "domicilio":"Las heras",
    "telefono": "9991387"

}

### Obtener socio por ID
DELETE  http://localhost:3000/api/socios/40


### Actualizar socio con PATCH (parcialmente)

PATCH http://localhost:3000/api/socios/4
Content-Type: application/json

{
    
    "email": "zephyrPvP@gmail.com"

}


### Actualizar socio con PUT

PUT http://localhost:3000/api/socios/4
Content-Type: application/json

{
    "nombre": "Juancho",
    "apellido": "Lopez",
    "email": "agosLopez@gmail.com",
    "domicilio":"Las heras"


}


