
### Obtener todos los libros
GET http://localhost:3000/api/libros/

### Subir libro

POST http://localhost:3000/api/libros
Content-Type: application/json

{
    "titulo": "Libro para borrar",
    "descripcion": "Un clásico de la literatura contemporanéa",
    "isbn": "0-7645-2641-3",
    "misAutores": [1],
    "miEditorial": 1,
    "cantEjemplares": 2

}

### Delete de un libro por ID

DELETE  http://localhost:3000/api/libros/-123




### Actualizar autor con PUT
PUT http://localhost:3000/api/libros/16
Content-Type: application/json

{
    "titulo": "Libro para borrar PUT",
    "descripcion": "Un clásico de la literatura contemporanéa",
    "isbn": "0-7645-2641-3",
    "misAutores": [1],
    "miEditorial": 1

}

### Actualizar autor con PATCH
PATCH http://localhost:3000/api/libros/16
Content-Type: application/json

{
    "titulo": "Libro PATCHEEE"

}