###obtener todas las sucuersales de los shelters 
GET http://localhost:3000/api/shelter

### obtener una sucurdal de algun shelter
GET http://localhost:3000/api/shelter/3

###crear un nuevo shelter
POST http://localhost:3000/api/shelter
Content-Type: application/json

{
    "nombre": "patas alegres 2", 
    "direccion": "calle falsa 2",
    "capacidadMaxima": 11,
    "id": "3"
}

### modificar un shelter(PUT)
PUT http://localhost:3000/api/shelter/2
Content-Type: application/json

{
    "nombre": "patas alegres 3", 
    "direccion": "utn",
    "capacidadMaxima": 100,
    "id": "2"
}

### modificar un shelter (PATCH - recurso parcial)
PATCH http://localhost:3000/api/shelter/3
Content-Type: application/json

{
    "nombre": "patitas",
    "direccion": "calle"
}

### borrar un shelter
DELETE http://localhost:3000/api/shelter/3