### Obtener todos los metodos de pago
GET http://localhost:3000/api/payment

### Obtener un metodo de pago
GET http://localhost:3000/api/payment/doge

### Crear un nuevo metodo de pago
POST http://localhost:3000/api/payment
Content-Type: application/json

{
    "name": "Dogecoin",
    "abv": "DOGE",
    "conv": 0.13,
    "id": "doge"
}

### Modificar un metodo de pago (PUT = Modificar todas los datos)
PUT http://localhost:3000/api/payment/doge
Content-Type: application/json

{
    "name": "Dogecoin",
    "abv": "DOGE",
    "conv": 0.16,
    "id": "doge"
}

### Eliminar un metodo de pago
DELETE http://localhost:3000/api/payment/ars
