### obtener todos los eventos

GET http://localhost:3000/api/evento

### obtener un evento

GET http://localhost:3000/api/evento/345345

### crear un nuevo evento

POST http://localhost:3000/api/evento
Content-Type: application/json

{
    "idEvento": "345345",
    "nombre":"Fiesta de cumpleaños",
    "cuposGral":40,
    "descripcion":"¡Es hora de festejar otro año de vida! Vení a la fiesta y hagamos de este cumpleaños algo inolvidable. ¡Diversión, amigos y sorpresas te esperan!",
    "fecha":"08/08/2025",
    "hora":15
}

### modificar un evento (PUT - recurso completo e inempotente)
PUT http://localhost:3000/api/evento/123123
Content-Type: application/json

{
    "nombre":"Despedida de soltero",
    "cuposGral":25,
    "descripcion":"¡Se viene la última noche de libertad! Te invitamos a la despedida de soltero de [nombre], una noche épica con amigos ¡Prepárate para una fiesta inolvidable!",
    "fecha":"23/02/2025",
    "hora":21
}



### modificar un evento (PATCH - recurso parcial)
PATCH http://localhost:3000/api/evento/123123
Content-Type: application/json

{
    "cuposGral": 35,
    "fecha":"22/06/2025"
}


### Borrar un evento
DELETE http://localhost:3000/api/evento/345345