###obtener todos las persons 
GET http://localhost:3000/api/person

###crear una nueva person
# @name createPerson
POST http://localhost:3000/api/person
Content-Type: application/json

{
    "name": "Otra",
    "surname":"person",
    "doc_type": "no tiene",
    "doc_nro": 0,
    "phone": "123456789",
    "birthdate": "01/01/2000",
    "address": "cualquiera",
    "nroCuit": 0
}

### ID
@id = {{createPerson.response.body.data.id}}

###obtener una person 
GET http://localhost:3000/api/person/{{id}}

### modificar una person (PUT)
PUT http://localhost:3000/api/person/{{id}}
Content-Type: application/json

{
    "name": "Otra",
    "surname":"person",
    "doc_type": "ahora si tiene",
    "doc_nro": "1",
    "phone": "123456789",
    "birthdate": "01/01/2000",
    "address": "corrientes",
    "nroCuit": 2019
}

### modificar una person (PATCH - recurso parcial)
PATCH http://localhost:3000/api/person/01
Content-Type: application/json

{
    "nroCuit":0,
    "address": "herreranico2703@gmail.com"
}

### borrar una person
DELETE http://localhost:3000/api/person/{{id}}