### Get all the specialties
GET http://localhost:3000/api/specialty


### POST
# @name createSpecialty
POST http://localhost:3000/api/specialties
Content-Type: application/json
{
    "name": "Obstreta"
}

### ID
@id = {{createSpecialty.response.body.data.id}}

### Get one specialty
GET http://localhost:3000/api/specialty/{{id}}

### Update a specialty
PUT http://localhost:3000/api/specialty/{{id}}
Content-Type: application/json

{
    "name": "Abortista"
}

### Delete a specialty
DELETE http://localhost:3000/api/specialty/{{id}}