// TODO: Al hacer update la contraseña no se hashea

// TODO: Al no introducir tipo por defecto tiene que establecerse en 'usuario'

// CREAR USUARIOS

### Usuario 1
PUT http://localhost:3000/api/usuarios/6556a8c6e9f6a54f3958714a
Content-Type: application/json

{
    "username": "martin_jasom",
    "nombre":"Martin",
    "apellido":"Jasom",
    "email":"JasonMtn@gmail.com",
    "direccion":"calle falsa 123",
    "localidad":"6556a826e9f6a54f39587147",
    "tipo":"Administrador",
    "contraseña": "contrasena2223"
}

### Usuario 2
PUT http://localhost:3000/api/usuarios/6556e650d4630d9628e3ebd2
Content-Type: application/json

{
    "username": "lucia_smithy",
    "nombre":"Lucia",
    "apellido":"Smithy",
    "email":"LuciaSmithy@email.com",
    "direccion":"avenida imaginaria 456",
    "localidad":"6556a826e9f6a54f39587147",
    "contraseña": "claveSegura789"
}

### CREAR USUARIO
POST http://localhost:3000/api/usuarios/
Content-Type: application/json

{
    "username": "marina_milo",
    "nombre":"Marina",
    "apellido":"Milo",
    "email":"milomarina51@gmail.com",
    "contraseña": "Marina12345"
}

### CREAR USUARIO
POST http://localhost:3000/api/usuarios/
Content-Type: application/json

{
    "username": "Alex_12",
    "nombre":"Alejo",
    "apellido":"Retamal",
    "email":"alejoretamal123@gmail.com",
    "contraseña": "Alejo12345",
    "tipo": "Adminr" // Esto sobra, para poner tu usuario como admin deberías modificarlo desde la base de datos.
}

### OBTENER USUARIO POR TOKEN
GET http://localhost:3000/api/usuarios/token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTVlMjcyN2EzYmI0ZWI2NGI2OWVhY2QiLCJpYXQiOjE3MDA2Nzg5MTAsImV4cCI6MTcwMDY4MjUxMH0.BUPnhOEISy7FTydqTNnfmwlG7cYUa3N8rQ-vRPiTy40

### OBTENER USUARIO POR USERNAME
GET http://localhost:3000/api/usuarios/username/marina_milo

### OBTENER USUARIO POR USERNAME
GET http://localhost:3000/api/usuarios/655e2727a3bb4eb64b69eacd

### BORRAR USUARIO
DELETE http://localhost:3000/api/usuarios/655e2727a3bb4eb64b69eacd

### OBTENER USUARIO POR ID
GET http://localhost:3000/api/usuarios/6561065f8a68d4ddd28c058b