// CREAR USUARIOS

### Usuario 1
PUT http://localhost:3000/api/usuarios/6556a8c6e9f6a54f3958714a
Content-Type: application/json

{
    "nombre":"Martin",
    "apellido":"Jasom",
    "email":"JasonMtn@gmail.com",
    "direccion":"calle falsa 123",
    "localidad":"6556a826e9f6a54f39587147",
    "tipo":"Administrador",
    "contraseña": "contrasena223445"
}

### Usuario 1
GET http://localhost:3000/api/usuarios
Content-Type: application/json