// CREAR EDITORIALES

### Editorial 1
PUT http://localhost:3000/api/editoriales/654bee46df333bf9237a1407
Content-Type: application/json

{
    "descripcion": "Pearson",
    "direccion": "Londres, Reino Unido",
    "imagen": "../../../../assets/img/Editoriales/Pearson.png"
}

### Editorial 2
PUT http://localhost:3000/api/editoriales/654bf9abdf333bf9237a1408
Content-Type: application/json

{
    "descripcion": "O'Reilly Media",
    "direccion": "Sebastopol, California, Estados Unidos",
    "imagen": "../../../../assets/img/Editoriales/OReilly.png"
}

### Editorial 3
PUT http://localhost:3000/api/editoriales/654bfa25df333bf9237a1409
Content-Type: application/json

{
    "descripcion": "Addison-Wesley Professional",
    "direccion": "Reading, Massachusetts, Estados Unidos",
    "imagen": "../../../../assets/img/Editoriales/Addison-Wesley.webp"
}

### Editorial 4
PUT http://localhost:3000/api/editoriales/654bfa69df333bf9237a140a
Content-Type: application/json

{
    "descripcion": "McGraw Hill",
    "direccion": "Nueva York, Estados Unidos",
    "imagen": "../../../../assets/img/Editoriales/McGraw-Hill.png"
}

### Editorial 5
PUT http://localhost:3000/api/editoriales/654bfac5df333bf9237a140b
Content-Type: application/json

{
    "descripcion": "Springer",
    "direccion": "Berlín, Alemania",
    "imagen": "../../../../assets/img/Editoriales/Springer.jpg"
}

###
GET http://localhost:3000/api/editoriales/

###
GET http://localhost:3000/api/editoriales/descripcion/654bee46df333bf9237a1407

###

GET http://localhost:3000/api/editoriales/descripciones/Pearson