

### Get de editorial
GET http://Localhost:3000/api/editoriales



### Get de editorial por nombre
GET http://Localhost:3000/api/editoriales/6522a452176057b2ea4ed843


### Post de editorial
POST http://localhost:3000/api/editoriales
Content-Type: application/json

{
    "name": "CrazyBooks",
    "categoria": "Pre-escolar",
    "id": "2"
}



### Delete de editorial
DELETE http://localhost:3000/api/editoriales/6522a452176057b2ea4ed843