### Get all the treatments
# @name createTreatment

GET http://localhost:3000/api/treatment

### Get one treatment
GET http://localhost:3000/api/treatment/001

### Create a treatments
POST http://localhost:3000/api/treatment
Content-Type: application/json

{
    "id": "002",
    "name": "Radiografia",
    "description": "toma imágenes de las estructuras internas del cuerpo"
}

### Update a treatment
PUT http://localhost:3000/api/treatment/002
Content-Type: application/json

{
    "name": "Quirofano",
    "description": "Lugar para realizar cirugias"
}

### Delete a tratment
DELETE http://localhost:3000/api/treatment/002