// CREAR TODOS LOS FORMATOS

### Formato 1
PUT http://localhost:3000/api/formato/654bfec19906829dff7bca04
Content-Type: application/json

{
    "descripcion": "Físico"
}

### Formato 2
PUT http://localhost:3000/api/formato/654bfee69906829dff7bca05
Content-Type: application/json

{
    "descripcion": "Digital"
}

### Formato 3
PUT http://localhost:3000/api/formato/654bfef79906829dff7bca07
Content-Type: application/json

{
    "descripcion": "Audiolibro"
}

### GetAll
GET http://localhost:3000/api/formato/
Content-Type: application/application/json

{
}