### Obtener todos los turnos

GET http://localhost:3000/api/turno

###Obtener turno por id

GET http://localhost:3000/api/turno/1

### Cargamos un turno

POST http://localhost:3000/api/turno
Content-Type: application/json

{
  "fechaHora": "2023-11-01T10:00:00.000Z",
  "estado": "pendiente",
  "servicio": 1,
  "usuario": 1
}

###Hacemos un PUT

PUT http://localhost:3000/api/turno/3
Content-Type: application/json

{
  "calificacion": 5,
  "comentario": "Excelente servicio"
}

### Hacemos un patch
PATCH http://localhost:3000/api/turno/1
Content-Type: application/json

{
  "estado": "completado"
}


###Hacemos un delete
DELETE http://localhost:3000/api/turno/1