// CREAR TODAS LAS CATEGORÍAS

### Categoría 1
PUT http://localhost:3000/api/categorias/654a87d434149a6f152448c6
Content-Type: application/json

{
    "descripcion": "Ficción"
}

### Categoría 2
PUT http://localhost:3000/api/categorias/654a87d534149a6f152448c7
Content-Type: application/json

{
    "descripcion": "No ficción"
}

### Categoría 3
PUT http://localhost:3000/api/categorias/654a87d734149a6f152448c8
Content-Type: application/json

{
    "descripcion": "Literatura infantil"
}

### Categoría 4
PUT http://localhost:3000/api/categorias/654a87d834149a6f152448c9
Content-Type: application/json

{
    "descripcion": "Educación y referencia"
}

### Categoría 5
PUT http://localhost:3000/api/categorias/654a87d934149a6f152448ca
Content-Type: application/json

{
    "descripcion": "Ciencia y naturaleza"
}

### Categoría 6
PUT http://localhost:3000/api/categorias/654a87da34149a6f152448cb
Content-Type: application/json

{
    "descripcion": "Religión y espiritualidad"
}

### Categoría 7
PUT http://localhost:3000/api/categorias/654a87db34149a6f152448cc
Content-Type: application/json

{
    "descripcion": "Política y sociedad"
}

### Categoría 8
PUT http://localhost:3000/api/categorias/654a87dc34149a6f152448cd
Content-Type: application/json

{
    "descripcion": "Salud y bienestar"
}

### Categoría 9
PUT http://localhost:3000/api/categorias/654a87dd34149a6f152448ce
Content-Type: application/json

{
    "descripcion": "Negocios y finanzas"
}