### obtener todos los characters
GET http://localhost:3000/api/modosEnvio

### obtener un character
GET http://localhost:3000/api/modosEnvio/c0acc804-bf9c-4897-bbdf-7901d8e63689


### crear un nuevo character
POST http://localhost:3000/api/modosEnvio
Content-Type: application/json

{
  "nombre": "Envia a Domicilio",
  "precio": 500
}

### modificar un character (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/modosEnvio/c0acc804-bf9c-4897-bbdf-7901d8e63689
Content-Type: application/json

{
    "nombre": "Envia domicilio gold",
    "precio": 800
}

### modificar un character (PATCH - recurso parcial)
PATCH http://localhost:3000/api/modosEnvio/c0acc804-bf9c-4897-bbdf-7901d8e63689
Content-Type: application/json

{
    "precio": 600
}

### borrar un character
DELETE http://localhost:3000/api/modosEnvio/17454e0a-4cd0-4daf-9330-5184036bd940
