### Obtener todos los usuarios

GET http://localhost:3000/api/usuario


GET http://localhost:3000/api/usuario/1

### Cargamos un usuario

POST http://localhost:3000/api/usuario
Content-Type: application/json

{
  "mail": "4luisParmigia@gmail.com",
  "contrasena": "123489sdfafgdfjasdhjahsd",
  "tipoDoc": "DNI",
  "numeroDoc": "1234567",
  "direccion": "Tenis 7884",
  "telefono": "12345689",
  "nombre": "4Luis",
  "apellido":"4Parmigiani"
}


###Hacemos un PUT

PUT http://localhost:3000/api/usuario/1
Content-Type: application/json

{
  "tiposDeServicio": [
    1
  ]
}

### Hacemos un patch
PATCH http://localhost:3000/api/usuario/1
Content-Type: application/json

{
  "nombre":"Agustin Ivan",
  "telefono":"5493496",
  "mail":"agutindana@hotmail.com"
}

### Hacemos un delete
DELETE http://localhost:3000/api/usuario/2

