### Obtener todos los usuarios

GET http://localhost:3000/api/usuario

###Obtener usuario por id

GET http://localhost:3000/api/usuario/

### Cargamos un usuario

POST http://localhost:3000/api/usuario
Content-Type: application/json

{
  "mail": "luisParmi@gmail.com",
  "contrasena": "123489sdfafgdfjasdhjahsd",
  "tipoDoc": "DNI",
  "numeroDoc": 45800900,
  "direccion": "Tenis 7884",
  "telefono": 341123456,
  "nombre": "Luis",
  "apellido":"Parmigiani"
}
###Hacemos un PUT

PUT http://localhost:3000/api/usuario/1
Content-Type: application/json

{
  
  "nombre":"Luis Parmani",
  "telefono":3413946,
  "mail":"luisParmi123123@gmail.com"
}

### Hacemos un patch
PATCH http://localhost:3000/api/usuario/1
Content-Type: application/json

{
  "nombre":"Agustin Ivan",
  "telefono":5493496,
  "mail":"agutindana@hotmail.com"
}

###HAcemos un delete
DELETE http://localhost:3000/api/usuario/
