# Generated by Django 4.1.5 on 2023-08-14 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nospeak_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='album',
        ),
        migrations.AddField(
            model_name='cancion',
            name='artista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nospeak_app.artista'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nro_seguidores',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Suscripcion',
        ),
    ]
