# Generated by Django 4.1.5 on 2023-08-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nospeak_app', '0002_remove_cancion_album_cancion_artista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nospeak_app.artista'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='spotify_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
