# Generated by Django 4.2.4 on 2023-08-18 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nospeak_app', '0003_album_artista_cancion_spotify_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='artista',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='cancion',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='cancion',
        ),
        migrations.RemoveField(
            model_name='recomendacion',
            name='cancion',
        ),
        migrations.RemoveField(
            model_name='recomendacion',
            name='playlist',
        ),
        migrations.AddField(
            model_name='cancion',
            name='album',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nospeak_app.album'),
        ),
        migrations.AddField(
            model_name='historial',
            name='canciones',
            field=models.ManyToManyField(to='nospeak_app.cancion'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='canciones',
            field=models.ManyToManyField(to='nospeak_app.cancion'),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='canciones',
            field=models.ManyToManyField(to='nospeak_app.cancion'),
        ),
        migrations.AlterField(
            model_name='album',
            name='portada',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nro_seguidores',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='anio_lanzamiento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='artista',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nospeak_app.artista'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='audio',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='spotify_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
        migrations.AlterField(
            model_name='historial',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nospeak_app.usuario'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nospeak_app.usuario'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nospeak_app.usuario'),
        ),
    ]
