# Generated by Django 4.2.4 on 2023-08-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nospeak_app', '0008_alter_playlist_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='portada',
            field=models.URLField(null=True),
        ),
    ]
