# Generated by Django 4.2.4 on 2023-08-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nospeak_app', '0009_playlist_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='fecha_reproduccion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
