# Generated by Django 4.2.4 on 2023-08-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nospeak_app', '0010_alter_historial_fecha_reproduccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='canciones',
            field=models.ManyToManyField(null=True, to='nospeak_app.cancion'),
        ),
    ]
