### Get all the users
GET http://localhost:3000/api/user

### Get one user
GET http://localhost:3000/api/user/4585666

### Create an user
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "id": "4585000",
    "fisrtName": "Jose",
    "lastName":"Cuack",
    "email": "jose@gmail.com",
    "password": "contrar",
    "age":27,
    "tuitionNumber":-1

 }   

### Update an user
PUT http://localhost:3000/api/user/4585000
Content-Type: application/json

{
    "firstName": "Ricarda",
    "email": "ricarda@gmail.com"
}

### Delete a user
DELETE http://localhost:3000/api/user/4585666