### Ver Provincias
GET http://localhost:3000/api/provincia/provincias

// CREAR PROVINCIAS

### Provincia 1
PUT http://localhost:3000/api/provincia/6556a42b682042abd14423e3
Content-Type: application/json

{
    "descripcion": "Santa Fe"
}

### Provincia 2
PUT http://localhost:3000/api/provincia/6556a4a7e8bf2517b0bbc6ab
Content-Type: application/json

{
    "descripcion": "Córdoba"
}

### Provincia 3
PUT http://localhost:3000/api/provincia/6556a4c8e8bf2517b0bbc6ac
Content-Type: application/json

{
    "descripcion": "Buenos Aires"
}

### Provincia 4
PUT http://localhost:3000/api/provincia/6556a4e6e8bf2517b0bbc6ad
Content-Type: application/json

{
    "descripcion": "Mendoza"
}