# Get all group_tasks
GET http://localhost:4000/api/group_tasks

###

# Create group_task
POST http://localhost:4000/api/group_tasks
Content-Type: application/json

{
  "groupId": 1,
  "conection": 1234,
  "tasks": [
    {
      "id": 1,
      "quantity": 2
    },
    {
      "id": 2,
      "quantity": 3
    }
  ],
  "dateCompleted": "2025-01-10",
  "hour": "12:00",
  "observation": "Observación"
}
