@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMywicm9sZSI6ImFkbWluIn0sImlhdCI6MTczNzUwMjY0NywiZXhwIjoxNzM4MTA3NDQ3fQ.Nv4WcTYz6Aw59i9Yigk3pqLJqhbtTpZRjYr6If01-Ok"

# Get all group_technicians
GET http://localhost:4000/api/group_technicians
Content-Type: application/json

{
  "token": {{token}}
}

###

# Get all group_technicians
GET http://localhost:4000/api/group_technicians/bussyGroups
Content-Type: application/json

{
  "token": {{token}}
}

###

# Get group_technician by group_id
GET http://localhost:4000/api/group_technicians/1
Content-Type: application/json

{
  "token": {{token}}
}

###

# Create group_technician
POST http://localhost:4000/api/group_technicians
Content-Type: application/json

{
  "groupId": 1,
  "technicianId": 1,
  "token": {{token}}
}

###

# Delete group_technician by group_id
DELETE http://localhost:4000/api/group_technicians/1
Content-Type: application/json

{
  "token": {{token}}
}