@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMywicm9sZSI6ImFkbWluIn0sImlhdCI6MTczNzUwMjY0NywiZXhwIjoxNzM4MTA3NDQ3fQ.Nv4WcTYz6Aw59i9Yigk3pqLJqhbtTpZRjYr6If01-Ok"

# Get all tasks
GET http://localhost:4000/api/tasks?page=1

###

# Get task by id
GET http://localhost:4000/api/tasks/1

###

# Update task by id
PUT http://localhost:4000/api/tasks/1
Content-Type: application/json

{
  "name": "Prueba",
  "price": 100,
  "token": {{token}}
}

###

# Create task
POST http://localhost:4000/api/tasks
Content-Type: application/json

{
  "name": "Prueba 123",
  "price": 100,
  "token": {{token}}
}

###

# Delete task by id
DELETE http://localhost:4000/api/tasks/1
Content-Type: application/json

{
  "token": {{token}}
}
