
### Obtener todos los autores
GET http://localhost:3000/api/autores


### Obtener un autor

GET http://localhost:3000/api/autores/046390cf-48b5-4274-a053-44a4d390ebb9

### Subir autor

POST http://localhost:3000/api/autores
Content-Type: application/json

{
    "nombre": "Maria Elena",
    "apellido": "Walsh"
}

### Actualizar autor con PUT

PUT http://localhost:3000/api/autores/505babb5-7635-4701-be80-3bce4647db2f
Content-Type: application/json

{
    "nombre": "Jorge Luis",
    "apellido": "Borges" 
  
}

### Actualizar autor con PATCH (parcialmente)

PATCH http://localhost:3000/api/autores/046390cf-48b5-4274-a053-44a4d390ebb9
Content-Type: application/json

{

    "apellido": "Montini"

}

### Delete de un autor por ID
DELETE  http://localhost:3000/api/autores/505babb5-7635-4701-be80-3bce4647db2f
