### Obtener todas las equipos
GET http://localhost:3000/api/equipos


### Obtener una equipo
GET http://localhost:3000/api/equipos/2


### Crear un nuevo equipo
POST http://localhost:3000/api/equipos
Content-Type: application/json

{
    "participantes": [],
    "partidos": [4],
    "torneo": 3
}


### Modificar una equipo (PUT - Recurso completo e idempotente)
PUT http://localhost:3000/api/equipos/1
Content-Type: application/json

{
    "participantes": [],
    "partidos": [],
    "torneo": 1
}


### Modificar una equipo (PATCH - Recurso parcial)
PATCH http://localhost:3000/api/equipos/15
Content-Type: application/json

{
    "participantes": [26, 27]
}


### Borrar una equipo
DELETE http://localhost:3000/api/equipos/56