###obtener todos los animales 
GET http://localhost:3000/api/animal

###crear un nuevo animal
POST http://localhost:3000/api/animal
Content-Type: application/json

{
    "name": "marta", 
    "rescue_date": "10-10-2020",
    "birth_date": "10-10-2020",
    "id": "2"
}

###obtener un animal 
GET http://localhost:3000/api/animal/1

### modificar un animal (PUT)
PUT http://localhost:3000/api/animal/2
Content-Type: application/json

{
    "name": "freya", 
    "rescue_date": "2004203",
    "birth_date": "25122013",
    "id": "2"
}

### modificar un animal (PATCH - recurso parcial)
PATCH http://localhost:3000/api/animal/1
Content-Type: application/json

{
    "rescue_date": "20 12 2020",
    "birth_date": "30 1 2016"
}

### borrar un animal
DELETE http://localhost:3000/api/animal/2