###obtener todos los animales 
GET http://localhost:3000/api/animal

###crear un nuevo animal
#  @name createAnimal
POST http://localhost:3000/api/animal
Content-Type: application/json

{
    "name": "marta", 
    "rescue_date": "2023-10-20",
    "birth_date": "2020-10-10",
    "breed": "1",
    "rescueClass": "2"
    
}

###ID
 @id = {{createAnimal.response.body.data.id}}
### obtener un animal 
GET http://localhost:3000/api/animal/{{{id}}}


### modificar un animal (PUT)
PUT http://localhost:3000/api/animal/2
Content-Type: application/json

{
    "name": "freya", 
    "rescue_date": "2004203",
    "birth_date": "25122013",
    "breed": "1"
}



### borrar un animal
### DELETE
@idToDelete = {{createAnimal .response.body.data.id}}
DELETE http://localhost:3000/api/animal/{{{{idToDelete}}}}