// CREAR TODOS LOS AUTORES

### Autor 1
PUT http://localhost:3000/api/autores/654a8a23e9bd128c04108bbb
Content-Type: application/json

{
    "nombreCompleto": "Robert C. Martin",
    "perfil": "http://localhost:4200/assets/img/Autores/RobertCMartin.jpg",
    "info": "Conocido como Uncle Bob, es un influyente ingeniero de software y autor de libros destacado en el desarrollo ágil y la programación limpia. Su enfoque práctico y sus libros, como Clean Code, han impulsado estándares de excelencia en la industria del software."
}

### Autor 2
PUT http://localhost:3000/api/autores/654a8b3de9bd128c04108bbc
Content-Type: application/json

{
    "nombreCompleto": "James Clear",
    "perfil": "http://localhost:4200/assets/img/Autores/James Clear.png",
    "info": "Es un escritor y conferencista reconocido por su trabajo en el campo del desarrollo personal y la mejora del rendimiento. Su libro Atomic Habits ha ganado popularidad al ofrecer consejos prácticos para construir hábitos duraderos y alcanzar el éxito personal y profesional."
}

### Autor 3
PUT http://localhost:3000/api/autores/654a8b3ee9bd128c04108bbd
Content-Type: application/json

{
    "nombreCompleto": "Mark Lutz",
    "perfil": "http://localhost:4200/assets/img/Autores/Mark Lutz.jpg",
    "info": "Es un reconocido autor y programador de software, ampliamente conocido por su trabajo en el campo de Python. Sus libros, incluido Learning Python, han sido recursos fundamentales para estudiantes y profesionales que buscan dominar el lenguaje de programación Python."
}

### Autor 4
PUT http://localhost:3000/api/autores/654a8b40e9bd128c04108bbe
Content-Type: application/json

{
    "nombreCompleto": "Luis Joyanes Aguilar",
    "perfil": "http://localhost:4200/assets/img/Autores/Luis Joyanes Aguilar.jpg",
    "info": "Es un destacado ingeniero informático y autor de renombre en el ámbito de la programación. Sus libros, como Programación en C y Fundamentos de Programación, han sido ampliamente utilizados en la enseñanza de la programación y la informática a nivel universitario y profesional."
}

### Autor 5
PUT http://localhost:3000/api/autores/654b88d627e5c1b5feb052c1
Content-Type: application/json

{
    "nombreCompleto": "Eric Matthes",
    "perfil": "http://localhost:4200/assets/img/Autores/Eric Matthes.jpg",
    "info": "Eric Matthes es profesor de ciencias, matemáticas y programación en un instituto en Alaska. Lleva escribiendo programas desde que tenía cinco años y es el autor de 'Python Flash Cards'."
}

### Autor 6
PUT http://localhost:3000/api/autores/654b893b27e5c1b5feb052c2
Content-Type: application/json

{
    "nombreCompleto": "Charles Petzold",
    "perfil": "http://localhost:4200/assets/img/Autores/Charles Petzold.jpg",
    "info": "Lleva 35 años escribiendo sobre programación, informática y ordenadores. Sus libros incluyen más de una docena de tutoriales de programación y 'The Annotated Turing: A Guided Tour through Alan Turing's Historic Paper on Computability and the Turing Machine'. Vive en la ciudad de Nueva York con su mujer, la historiadora y novelista Deirdre Sinnott, y dos gatos llamados Honey y Heidi."
}

### Autor 7
PUT http://localhost:3000/api/autores/654b899927e5c1b5feb052c3
Content-Type: application/json

{
    "nombreCompleto": "John Ousterhout",
    "perfil": "http://localhost:4200/assets/img/Autores/John Ousterhout.jpg",
    "info": "John Kenneth Ousterhout es el presidente de Electric Cloud, Inc. y profesor de ciencias computacionales en la Universidad de Stanford. Fundó Electric Cloud con John Graham-Cumming."
}

### Autor 8
PUT http://localhost:3000/api/autores/654b8a3f27e5c1b5feb052c4
Content-Type: application/json

{
    "nombreCompleto": "Titus Winters",
    "perfil": "http://localhost:4200/assets/img/Autores/Titus Winters.jpg",
    "info": "Titus Winters es un destacado ingeniero de software y autor conocido por su papel fundamental en el desarrollo y la promoción de prácticas de ingeniería de software efectivas. Reconocido por su experiencia en sistemas de software a gran escala, ha desempeñado un papel crucial en la evolución de la infraestructura de código abierto en Google."
}

### Autor 9
PUT http://localhost:3000/api/autores/654b8f4827e5c1b5feb052c5
Content-Type: application/json

{
    "nombreCompleto": "Neal Ford",
    "perfil": "http://localhost:4200/assets/img/Autores/Neal Ford.jpg",
    "info": "Sus libros y presentaciones han inspirado a una amplia audiencia de profesionales de la informática y han contribuido significativamente a la evolución del panorama tecnológico actual. Además de sus logros como autor, Neal Ford ha desempeñado un papel importante en el asesoramiento y la consultoría para diversas empresas líderes en tecnología, consolidando su reputación como un experto influyente en la comunidad tecnológica."
}

### Autor 10
PUT http://localhost:3000/api/autores/654b8fd827e5c1b5feb052c6
Content-Type: application/json

{
    "nombreCompleto": "Daniel Zingaro",
    "perfil": "http://localhost:4200/assets/img/Autores/Daniel Zingaro.jpg",
    "info": "Daniel Zingaro es profesor asociado en la Universidad de Toronto Mississauga. Sus principales áreas de investigación son la evaluación de la educación en informática y el aprendizaje en línea."
}

### Autor 11
PUT http://localhost:3000/api/autores/654d44461de02c673186f9ae
Content-Type: application/json

{
    "nombreCompleto": "Andrew S. Tanenbaum",
    "perfil": "http://localhost:4200/assets/img/Autores/Andrew S. Tanenbaum.jpg",
    "info": "Andrew Stuart 'Andy' Tanenbaum, también conocido como ast o Papá Tanenbaum, es profesor de ciencias de la computación de la Universidad Libre de Ámsterdam, Países Bajos. Tanenbaum es conocido por ser el creador de Minix, una réplica gratuita del sistema operativo UNIX con propósitos educativos."
}

### Autor 12
PUT http://localhost:3000/api/autores/654d45481de02c673186f9b0
Content-Type: application/json

{
    "nombreCompleto": "Erich Gamma",
    "perfil": "http://localhost:4200/assets/img/Autores/Erich Gamma.jpg",
    "info": "Erich Gamma es un informático suizo. Es actualmente empleado de Microsoft tras pasar por IBM Rational software y ser director del Object Technology International Zurich Lab en Zúrich liderando el desarrollo de la plataforma Eclipse. Formó parte del grupo de los cuatro que popularizaron los patrones de diseño."
}

### Autor 13
PUT http://localhost:3000/api/autores/654d47141de02c673186f9b1
Content-Type: application/json

{
    "nombreCompleto": "John Vlissides",
    "perfil": "http://localhost:4200/assets/img/Autores/John Vlissides.jpg",
    "info": "John Matthew Vlissides fue un ingeniero de software conocido principalmente como uno de los cuatro autores del libro Design Patterns: Elements of Reusable Object-Oriented Software. Vlissides se refirió a sí mismo como '#4 de la Banda de los Cuatro y no lo tendría de otra manera'."
}

### Autor 14
PUT http://localhost:3000/api/autores/654d47fd1de02c673186f9b2
Content-Type: application/json

{
    "nombreCompleto": "Richard Helm",
    "perfil": "http://localhost:4200/assets/img/Autores/Perfil Default.jpg",
    "info": "Richard Helm es uno de la 'banda de los cuatro' que escribió el influyente libro Design Patterns. En 2006 recibió el Premio Dahl-Nygaard por sus contribuciones al estado del arte plasmado en ese libro."
}

### Autor 15
PUT http://localhost:3000/api/autores/654d487b1de02c673186f9b3
Content-Type: application/json

{
    "nombreCompleto": "Ralph Johnson",
    "perfil": "http://localhost:4200/assets/img/Autores/Ralph Johnson.jpg",
    "info": "Ralph E. Johnson es profesor asociado de investigación en el Departamento de Ciencias de la Computación de la Universidad de Illinois en Urbana-Champaign."
}

### PRUEBA
POST http://localhost:3000/api/autores/
Content-Type: application/json

{
    "nombreCompleto": "Autor de prueba",
    "perfil": "http://localhost:4200/assets/img/Autores/Ralph Johnson.jpg",
    "info": "Ralph E. Johnson es profesor asociado de investigación en el Departamento de Ciencias de la Computación de la Universidad de Illinois en Urbana-Champaign."
}